// This file was autogenerated by lib/closure/library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../../js/src/FirebaseTokenGenerator.js', ['FirebaseTokenGenerator'], ['CryptoJS', 'fb.tokengenerator.constants', 'fb.tokengenerator.json', 'fb.tokengenerator.utf8', 'fb.tokengenerator.validation', 'goog.crypt.base64']);
goog.addDependency('../../../../../js/src/constants.js', ['fb.tokengenerator.constants'], []);
goog.addDependency('../../../../../js/src/cryptojs.js', ['CryptoJS'], []);
goog.addDependency('../../../../../js/src/json.js', ['fb.tokengenerator.json'], ['goog.json']);
goog.addDependency('../../../../../js/src/utf8.js', ['fb.tokengenerator.utf8'], []);
goog.addDependency('../../../../../js/src/validation.js', ['fb.tokengenerator.validation'], []);
